backend:
  name: github
  repo: Miguel-AlexRaSa/alexrasa.store   # 🔹 pon aquí el NOMBRE EXACTO de tu repo en GitHub
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "assets/blog"     # donde se guardan las imágenes
public_folder: "/assets/blog"

collections:
  - name: "posts"
    label: "Publicaciones"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción corta", name: "description", widget: "string" }
      - { label: "Imagen principal", name: "image", widget: "image" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Contenido", name: "body", widget: "markdown" }
