backend:
  name: git-gateway
  branch: main
  base_url: https://deluxe-twilight-abb373.netlify.app
  auth_endpoint: /.netlify/identity

media_folder: "assets/blog"
public_folder: "/assets/blog"

collections:
  - name: posts
    label: Publicaciones
    folder: blog/posts
    create: true
    slug: "{{slug}}"
    extension: html
    format: frontmatter
    fields:
      - { label: "Título", name: title, widget: string }
      - { label: "Descripción corta", name: description, widget: string }
      - { label: "Imagen principal", name: image, widget: image }
      - { label: "Fecha", name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: "Contenido", name: body, widget: markdown }
